# OpenAI API Configuration
[openai]
api_key = "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"



# Trainer Configuration
[trainer]
password = "09031993"


